guineapigs/private/views.py
"""
    web routes for logged in user
"""
import heapq
from flask import (
    Blueprint,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required, logout_user
from guineapigs import models
from guineapigs.extensions import db
from guineapigs.private import forms
from guineapigs.utils import (
    beginning_of_day_utc,
    beginning_of_week_utc,
    date_to_datetime,
    next_day,
)

blueprint = Blueprint("private", __name__, static_folder="../static")


@blueprint.route("/logout")
@login_required
def logout_view():
    """
    logs user out and redirects them to home
    """
    logout_user()
    return redirect(url_for("public.login"))


@blueprint.route("/")
@login_required
def dashboard():
    """
    displays dashboard with vitamin c info, today's food entries and stats,
    and guinea pig weights
    """
    return render_template(
        "dashboard.html",
        food_entries=models.FoodEntry.get_in_time_range(beginning_of_day_utc()),
        vitamin_c=models.VitaminCEntry.get_today(),
    )


@blueprint.route("/history", methods=["GET", "POST"])
@login_required
def history():
    """
    displays history of all entries
    """
    today = beginning_of_day_utc()
    beginning_of_week = beginning_of_week_utc()
    form = forms.HistoryForm(request.form)

    start = end = None

    if request.method == "GET":
        start = beginning_of_week
        end = today
        form.start.data = beginning_of_week.date()
        form.end.data = today.date()
    elif form.validate():
        start = date_to_datetime(form.start.data)
        end = date_to_datetime(form.end.data)

    entries = []
    if start and end:
        end = next_day(end)
        food_entries = models.FoodEntry.get_in_time_range(start, end)
        weight_entries = models.WeightEntry.get_in_time_range(start, end)
        vitamin_c_entries = models.VitaminCEntry.get_in_time_range(start, end)

        food_entries = (
            (
                f.utc_date,
                "🍽️",
                f.food_type.label,
                ", ".join(gp.name for gp in f.guinea_pigs),
                f.user.name,
            )
            for f in food_entries
        )
        weight_entries = (
            (w.utc_date, "⚖️", w.value, w.guinea_pig.name, w.user.name,)
            for w in weight_entries
        )
        vitamin_c_entries = (
            (v.utc_date, "🌻", "", "", v.user.name,) for v in vitamin_c_entries
        )
        entries = heapq.merge(food_entries, weight_entries, vitamin_c_entries)

    return render_template("history.html", form=form, entries=entries)


@blueprint.route("/statistics")
@login_required
def statistics():
    """
    displays statistics page with weight info and food stats
    """
    return render_template(
        "statistics.html",
        status=models.FoodEntry.get_statistics(),
        weights=models.WeightEntry.get_most_recent(),
    )


@blueprint.route("/settings")
@login_required
def settings():
    """
    displays settings page to edit guinea pigs and food types
    """
    return render_template(
        "settings.html",
        food_types=models.FoodType.query.order_by("label").all(),
        guinea_pigs=models.GuineaPig.query.order_by(models.GuineaPig.name).all(),
    )


@blueprint.route("/vitaminc")
@login_required
def vitaminc():
    """
    adds vitaminc entry if it doesn't exist already
    """
    if models.VitaminCEntry.get_today():
        models.VitaminCEntry.delete_today()
    else:
        entry = models.VitaminCEntry()
        entry.user = current_user
        db.session.add(entry)
    db.session.commit()
    return redirect(url_for("private.dashboard"))


@blueprint.route("/food_entry/delete", methods=["POST"])
@login_required
def delete_food_entry():
    """
    deletes FoodEntry row and clears its relationship
    with guinea pigs
    """
    if food_entry_id := request.form.get("id"):
        if food_entry_id.isdecimal():
            entry = models.FoodEntry.query.filter(
                models.FoodEntry.id == int(food_entry_id)
            )
            entry.first().guinea_pigs = []
            entry.delete()
            db.session.commit()
    return redirect(url_for("private.dashboard"))


@blueprint.route("/food_entry/add", methods=["GET", "POST"])
@blueprint.route("/food_entry/edit/<int:id_>", methods=["GET", "POST"])
@login_required
def food_entry_form(id_=None):
    """
    inserts/edits a food entry
    """
    form = forms.FoodEntryForm()
    form.food_type_id.choices = [
        (food_entry.id, food_entry.label)
        for food_entry in models.FoodType.query.order_by(models.FoodType.label)
        .filter(models.FoodType.is_hidden == False) # pylint: disable=singleton-comparison
        .all()
    ]
    form.guinea_pig_ids.choices = [
        (guinea_pig.id, guinea_pig.name)
        for guinea_pig in models.GuineaPig.query.order_by(models.GuineaPig.name).all()
    ]

    entry = None
    if id_:
        entry = models.FoodEntry.query.filter(models.FoodEntry.id == id_).first()

    if form.validate_on_submit():

        entry = entry or models.FoodEntry()
        entry.food_type_id = form.food_type_id.data
        entry.notes = form.notes.data
        entry.user = current_user
        entry.guinea_pigs = models.GuineaPig.query.filter(
            models.GuineaPig.id.in_(form.guinea_pig_ids.data)
        ).all()
        db.session.add(entry)
        db.session.commit()
        return jsonify(status="ok")

    if entry:
        form.food_type_id.data = entry.food_type_id
        form.notes.data = entry.notes
        form.guinea_pig_ids.data = [guinea_pig.id for guinea_pig in entry.guinea_pig]
    else:
        form.guinea_pig_ids.data = [
            guinea_pig[0] for guinea_pig in form.guinea_pig_ids.choices
        ]

    return render_template("forms/food_entry_form.html", food_entry_form=form)


@blueprint.route("/weight_entry/add", methods=["GET", "POST"])
@blueprint.route("/weight_entry/edit/<int:id_>", methods=["GET", "POST"])
@login_required
def weight_entry_form(id_=None):
    """
    insert/edit a weight entry
    """
    form = forms.WeightEntryForm()
    form.guinea_pig_id.choices = [
        (guinea_pig.id, guinea_pig.name)
        for guinea_pig in models.GuineaPig.query.order_by(models.GuineaPig.name).all()
    ]

    entry = None
    if id_:
        entry = models.WeightEntry.query.filter(models.WeightEntry.id == id_).first()

    if form.validate_on_submit():
        entry = entry or models.WeightEntry()
        entry.value = float(form.value.data)
        entry.guinea_pig_id = form.guinea_pig_id.data
        entry.user = current_user
        db.session.add(entry)
        db.session.commit()
        return jsonify(status="ok")

    if entry:
        form.value.data = entry.value
        form.guinea_pig_id.data = entry.guinea_pig_id

    return render_template("forms/weight_entry_form.html", weight_entry_form=form)


@blueprint.route("/guinea_pig/add", methods=["GET", "POST"])
@blueprint.route("/guinea_pig/edit/<int:id>", methods=["GET", "POST"])
@login_required
def guinea_pig_form(id_=None):
    """
    insert/edit guinea pigs
    """
    form = forms.GuineaPigForm()
    guinea_pig = None
    if id_:
        guinea_pig = models.GuineaPig.query.filter(models.GuineaPig.id == id_).first()

    if form.validate_on_submit():
        guinea_pig = guinea_pig or models.GuineaPig()
        guinea_pig.name = form.name.data
        db.session.add(guinea_pig)
        db.session.commit()
        return jsonify(status="ok")

    if guinea_pig:
        form.name.data = guinea_pig.name

    return render_template("forms/guinea_pig_form.html", guinea_pig_form=form)


@blueprint.route("/food_type/add", methods=["GET", "POST"])
@blueprint.route("/food_type/edit/<int:id_>", methods=["GET", "POST"])
@login_required
def food_type_form(id_=None):
    """
    insert/edit guinea pigs
    """
    form = forms.FoodTypeForm()
    food_entry = None

    if id_:
        food_entry = models.FoodType.query.filter(models.FoodType.id == id_).first()

    if form.validate_on_submit():
        food_entry = food_entry or models.FoodType()
        food_entry.label = form.label.data
        food_entry.recommendations = form.recommendations.data
        food_entry.is_hidden = form.is_hidden.data
        food_entry.in_statistics = form.in_statistics.data
        db.session.add(food_entry)
        db.session.commit()
        return jsonify(status="ok")

    if food_entry:
        form.label.data = food_entry.label
        form.recommendations.data = food_entry.recommendations
        form.is_hidden.data = food_entry.is_hidden
        form.in_statistics.data = food_entry.in_statistics

    return render_template("forms/food_type_form.html", food_type_form=form)

guineapigs/templates/base.html
<!doctype html>
<html lang="en">

<head>
  {% block head %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <title>{{ config["TITLE"] }}</title>
  {% endblock %}
</head>

<body>
  {% include "navbar.html" %}
  <div class="container">
    {% if current_user.is_authenticated %}
	<h5 class="text-right my-4">
		<span class="bg-light border border-primary p-2 rounded">
		hi, {{current_user.name}}!
		</span>
	</h5>
    {% endif %}
    {% block content %}{% endblock %}
    <div id="modal" class="modal fade" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div id="modal-content" class="modal-content">
        </div>
      </div>
	</div>
    {% block footer %}{% endblock %}
  </div>

  <script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>

</html>

guineapigs/templates/dashboard.html
{% extends "base.html" %}
{% block content %}
<div class="card text-white bg-{% if vitamin_c %}primary{% else %}secondary{% endif %} my-3">
	<div class="card-header">
		<h5>vitamin c</h5>
	</div>
	<div class="card-body">
			<h4 class="card-title"><a href="{{ url_for("private.vitaminc") }}" class="bg-white text-decoration-none rounded mr-2 py-1 px-2"><span{% if not vitamin_c %} style="opacity: 0"{% endif %}>&#10004;</span></a>vitamin c {% if not vitamin_c %}not {% endif %}fulfilled</h4>
		{% if vitamin_c %}
		<p class="card-text">given today @ {{ strftime(vitamin_c.utc_date, "%l:%M %p") }} by {{ vitamin_c.user.name }}</p>
		{% endif %}
	</div>
</div>

<div class="card border-secondary bg-light my-3">
	<div class="card-header d-flex justify-content-between align-items-center">
		<h5>food entries</h5>
		<form class="modal-form" action="/food_entry/add">
			<button class="btn btn-secondary modal-btn" type="button">&plus; add</button>
		</form>
	</div>
	<div class="list-group-flush card-body">
	{% for entry in food_entries|sort(reverse=True) %}
	<div class="list-group-item bg-light d-flex w-100 justify-content-between px-0">
    	<div class="w-100">
      		<div class="d-flex w-100 justify-content-between">
        		<h5 class="mb-1 align-self-center">{{ entry.food_type.label }}</h5>
        		<p class="small align-self-start text-right mb-0 ml-2">{{ strftime(entry.utc_date, "%l:%M %p") }} by {{ entry.user.name }}</p>
      		</div>
      {% if entry.notes %}
      <p class="mb-0">
        <em>
          {{ entry.notes }}
        </em>
      </p>
      {% endif %}
    </div>
    <form class="align-self-start" action="/food_entry/delete" method="post">
      <input type="hidden" name="id" value="{{ entry.id }}">
	  <button type="submit" style="font-size: 1.8rem;text-decoration: none;"
        class="btn p-0 ml-1 btn-lg btn-link text-danger">&times;</button>
    </form>
  </div>
	{% else %}
	<h4 class="text-center">
		no food yet &gt;:(
	</h4>
	{% endfor %}
	</div>
</div>
{% endblock %}

guineapigs/templates/history.html
{% from 'bootstrap/wtf.html' import form_field %}
{% extends "base.html" %}
{% block content %}
<div class="card bg-light my-3">
	<div class="card-header">
		<h5>search</h5>
	</div>
	<div class="card-body">
		<form class="mt-2 mx-auto" action="/history" method="POST">
			{{ form.csrf_token }}
			{{ form_field(form.start) }}
			{{ form_field(form.end) }}
			<button type="submit" class="btn btn-primary btn-lg btn-block">search</button>
		</form>
	</div>
</div>

<div class="card bg-light my-3">
	<div class="card-header">
		<h5>results</h5>
	</div>
	<div class="card-body overflow-auto">
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">time</th>
					<th scope="col">type</th>
					<th scope="col">value</th>
					<th scope="col">guinea pigs</th>
					<th scope="col">person</th>
				</tr>
			</thead>
			<tbody>
				{% for date, type, value, guinea_pigs, user in entries|sort(reverse=True)  %}
				<tr>
					<th scope="row">{{ strftime(date, "%Y-%m-%d %H:%M %p") }}</th>
					<td>{{ type }}</td>
					<td>{{ value }}</td>
					<td>{{ guinea_pigs }}</td>
					<td>{{ user }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

guineapigs/templates/login.html
{% from 'bootstrap/wtf.html' import form_field %}
{% extends "base.html" %}
{% block content %}
<div class="card bg-light my-3">
	<div class="card-header">
		<h4>Log in</h4>
	</div>
	<div class="card-body">
		<form class="mt-2 mx-auto" style="max-width: 300px;" action="{{ url_for('public.login', next=request.args.get('next')) }}" method="POST">
			{{ login_form.csrf_token }}
			{{ form_field(login_form.name) }}
			<button type="submit" class="btn btn-primary btn-lg btn-block mt-1">save</button>
		</form>
	</div>
</div>
{% endblock %}

guineapigs/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
	<a class="navbar-brand" href="/">{{ config["TITLE"] }}</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
	</button>
	<div class="navbar-collapse collapse" id="navbarNav">
			<ul class="navbar-nav">
			  {% for label, view in (config["NAV_PAGES_LOGGED_IN"] if current_user.is_authenticated else config["NAV_PAGES_LOGGED_OUT"]) %}
			  <li class="nav-item">
					  <a class="nav-link{% if request.path == url_for(view) %} active{% endif %}" href="{{ url_for(view) }}">{{ label }}</a>
			  </li>
			  {% endfor %}
			</ul>
	</div>
	{% block navbar %}{% endblock %}
</nav>

guineapigs/templates/setname.html
{% extends "base.html" %}
{% block content %}
<form class="mt-2 mx-auto" style="max-width: 300px;" action="/setname" method="POST">
	<label for="name">Please enter your name:</label>
	<input class="form-control form-control-lg" id="name" name="name" type="text" placeholder="Name">
	<button type="submit" class="btn btn-primary btn-lg btn-block mt-1">Save</button>
</form>
{% endblock %}

guineapigs/templates/settings.html
{% extends "base.html" %}
{% block content %}
<div class="card bg-light border-secondary my-3">
	<div class="card-header d-flex justify-content-between align-items-center">
		<h5>guinea pigs</h5>
		<form class="modal-form" action="/guinea_pig/add">
			<button class="btn btn-secondary modal-btn" type="button">&plus; add</button>
		</form>
	</div>
	{% for gp in guinea_pigs %}
	<div class="card-body">
		<h4 class="card-title">{{ gp.name }}</h4>
	</div>
	{% else %}
	<div class="card-body">
		<h4 class="Title">No guinea pigs registered</h4>
	</div>
	{% endfor %}
</div>
<div class="card bg-light border-primary my-3">
	<div class="card-header d-flex justify-content-between align-items-center">
		<h5>food types</h5>
		<form class="modal-form" action="/food_type/add">
			<button class="btn btn-primary modal-btn" type="button">&plus; add</button>
		</form>
	</div>
	{% for food_type in food_types %}
	<div class="card-body d-flex justify-content-between">
		<div>
			<h4 class="card-title">{{ food_type.label }}</h4>
			{% if food_type.recommendations %}
			<p class="card-text"><b>Recommendations:</b> {{ food_type.recommendations }}</p>
			{% endif %}
		</div>
		<form action="/food_type/edit/{{ food_type.id }}">
			<button class="modal-btn btn btn-info">edit</button>
		</form>
	</div>
	{% else %}
	<div class="card-body">
		<h4 class="Title">No food registered</h4>
	</div>
	{% endfor %}
</div>
{% endblock %}

guineapigs/templates/statistics.html
{% extends "base.html" %}
{% block content %}
<div class="card bg-primary text-white my-3">
	<div class="card-header d-flex justify-content-between align-items-center">
		<h5>statistics</h5>
		<form class="modal-form" action="/weight_entry/add">
			<button class="btn btn-secondary modal-btn" type="button">&plus; log weight</button>
		</form>
	</div>
	<div class="card-body">
		<h4 class="card-title">food statistics</h4>
		{% for key, value in status.items() %}
		<p class="card-text"><span class="font-weight-bold">{{ key }}: </span>{{ value }}</p>
		{% endfor %}
	</div>
	{% for gp_name, weight in weights %}
	<div class="card-body">
		<h4 class="card-title">{{ gp_name }}</h4>
		<p class="card-text"><span class="font-weight-bold">weight: </span>{% if weight %}{{ weight }}g{% else %}Unknown{% endif %}</p>
	</div>
	{% else %}
	<div class="card-body">
		<h4 class="Title">No guinea pigs registered</h4>
	</div>
	{% endfor %}
</div>
{% endblock %}